# Generated by Django 5.2.4 on 2025-07-05 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_cart_deliveryoptionid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryoption',
            name='deliveryDays',
            field=models.CharField(choices=[(7, '7 days'), (3, '3 days'), (1, '1 Day')], max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='cartId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='products.cart'),
        ),
    ]
