# Generated by Django 5.2.4 on 2025-07-05 19:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_deliveryoption_deliverydays_alter_order_cartid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('user', 'cartNumber')},
        ),
        migrations.RemoveField(
            model_name='cart',
            name='deliveryOptionId',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='productId',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
    ]
