# Generated by Django 5.2.4 on 2025-07-05 19:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_cart_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('quantity', models.IntegerField(default=1)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('cartId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartid', to='products.cart')),
                ('deliveryOptionId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.deliveryoption')),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.product')),
            ],
            options={
                'unique_together': {('cartId', 'productId')},
            },
        ),
    ]
