# Generated by Django 5.2.4 on 2025-07-05 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_cartproduct_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='userId',
        ),
    ]
