# Generated by Django 5.2.4 on 2025-07-05 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_cart_is_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
