# Generated by Django 5.2.4 on 2025-07-05 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_cartproduct_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cartId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='products.cart', unique=True),
        ),
    ]
