# Generated by Django 5.2.4 on 2025-07-05 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_order_cartid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='deliveryOptionId',
        ),
        migrations.AddField(
            model_name='deliveryoption',
            name='cartId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cartdevlivery', to='products.cartproduct', unique=True),
            preserve_default=False,
        ),
    ]
