# Generated by Django 5.2.4 on 2025-07-06 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_cartproduct_deliveryoptionid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryoption',
            name='deliveryDays',
            field=models.CharField(choices=[(7, '7 days'), (3, '3 days'), (1, '1 Day')], default='7', max_length=10),
        ),
    ]
